FROM tomcat:10-jdk17
WORKDIR /usr/local/tomcat/webapps

ARG SECRET
ARG DATABASE_PASSWORD
ARG DATABASE_URL
ARG DATABASE_USERNAME

ENV SECRET = ${SECRET}
ENV DATABASE_PASSWORD=${DATABASE_PASSWORD}
ENV DATABASE_URL=${DATABASE_URL}
ENV DATABASE_USERNAME=${DATABASE_USERNAME}

COPY ./target/adm-usuarios.war .
EXPOSE 8080
