FROM tomcat:10-jdk17
WORKDIR /usr/local/tomcat/webapps

ARG API_FUNC_LOGIN
ARG API_FUNC_PASSWORD
ARG DATABASE_PASSWORD
ARG DATABASE_URL
ARG DATABASE_USERNAME

ENV API_FUNC_LOGIN=${API_FUNC_LOGIN} \
    API_FUNC_PASSWORD=${API_FUNC_PASSWORD} \
    DATABASE_PASSWORD=${DATABASE_PASSWORD} \
    DATABASE_URL=${DATABASE_URL} \
    DATABASE_USERNAME=${DATABASE_USERNAME}

COPY ./target/adm-usuarios.war .
EXPOSE 8080
